"""08.23.2.SCHILD: Tabellen- + Spalten-COMMENTs (Schilder) fuer public/crm/training.

op.execute COMMENT-only (Cross-AI-Finding 1, hauseigenes Muster aller 14 Migrationen). KEINE
Struktur-Aenderung (kein DROP/CREATE/ALTER TYPE). Die COMMENT-Texte sind die Single-Source
models.py comment= Werte (Plan 02+03); training.transcript_archive (ORM-los) ist eine weitere
op.execute-Gruppe mit hand-geschriebenem Text (0008-Schema). downgrade() setzt COMMENTs auf NULL
(reversibel, kein Daten-/Strukturverlust, D-04).

Revision ID: 0015
Revises: 0014
"""
from alembic import op

revision = '0015'
down_revision = '0014'
branch_labels = None
depends_on = None


# (schema, table, comment)
TABLE_COMMENTS = [
    ('public', 'organisations', 'Mandant/Organisation = Abrechnungs- und Daten-Isolations-Einheit (Plan, Fair-Use, Stripe). Status: lebt (Kern-Identitaet). Schreibt/liest routes/auth.py, routes/billing/-Pfade und services/.'),
    ('public', 'users', 'Nutzer-Konto innerhalb einer Organisation (Auth, Rolle, Onboarding, Usage, OAuth). Status: lebt (Kern-Identitaet). Schreibt/liest routes/auth.py, routes/onboarding/, services/ ueberall via g.user.'),
    ('public', 'profiles', 'Verkaeufer-Wissen/Methodik-Profil je Organisation (JSON-Methodik-Container daten). Status: lebt. Schreibt/liest routes/profiles.py; daten gelesen in live_session.set_active_profile.'),
    ('public', 'profile_skripte', 'Skript-Bausteine je Profil (Gespraechsleitfaeden, ggf. personalisiert). Status: lebt. Schreibt/liest routes/profiles.py; PreCall-Personalisierung in services/.'),
    ('public', 'profile_faqs', 'FAQ-Eintraege je Profil (Frage-Muster -> Antwort, fuer Live-Antwort-Vorschlaege). Status: lebt. Schreibt/liest routes/profiles.py; gelesen im Live-Loop services/.'),
    ('public', 'profile_opener', 'Gespraechs-Opener/Einstiegs-Bausteine je Profil (ggf. personalisiert). Status: lebt. Schreibt/liest routes/profiles.py; PreCall-Personalisierung in services/.'),
    ('public', 'sessions', 'DB-Token-Session (DbSession) — Auth nutzt jedoch Flask-Session, nicht diese Tabelle. Status: write-only [ZOMBIE]. Schreibt routes/auth.py:134; KEIN Reader.'),
    ('public', 'invitations', 'Einladungs-Token fuer neue Team-Mitglieder einer Organisation. Status: lebt. Schreibt/liest routes/ (Org-/Team-Verwaltung) ueber Token.'),
    ('public', 'billing_events', 'Abrechnungs-Ereignisse pro Organisation (Stripe-Webhooks, Betraege). Status: lebt. Schreibt Billing-/Stripe-Webhook-Pfad; liest Abrechnungs-/Founder-Ansichten.'),
    ('public', 'feedback_events', 'Stern-Feedback zu einer Session (Legacy-Feedback-Kanal). Status: write-only [ZOMBIE]. Schreibt routes/app_routes.py:1253; kein Reader.'),
    ('public', 'coach_assignments', 'Zuordnung Coach <-> Organisation (Coach-Plattform fuer Teams). Status: lebt. Schreibt/liest routes/coach.py.'),
    ('public', 'training_scenarios', 'Trainings-Szenario-Konfiguration je Organisation (Kunden-Situation/Verhalten/Einwaende fuer KI-Training). Status: lebt. Schreibt/liest routes/training.py; gelesen in services/training_service.py.'),
    ('public', 'personality_types', 'Persoenlichkeitstyp-Konfiguration fuer Personality-driven Training (Standard + Custom). Status: lebt. Schreibt/liest routes/training.py; gelesen im Trainings-Loop services/.'),
    ('public', 'conversation_logs', 'Persistenter Call-Datensatz mit aggregierter Post-Call-Analyse (Einwaende, Redeanteil, KB-Verlauf). RUECKGRAT des Call-Analyse-Clusters mit 6 Kindern. Status: lebt (TAXO-Umbau-Zone). Schreibt routes/app_routes.py (end_session); liest routes/dashboard.py, routes/learning.py.'),
    ('public', 'phrases', 'Anonymisierte Einwand-Phrasen aus Calls als Trainings-/Muster-Korpus (DSGVO-Pipeline). Status: lebt. Schreibt services/-Anonymisierungs-Pipeline (Phase 08.23.2.B); liest Muster-/Klassifikator-Pfad.'),
    ('public', 'waitlist', 'Early-Access-Warteliste mit Position und Referral-Tracking. Status: lebt. Schreibt Landing-/Waitlist-Pfad; liest Admin-/Invite-Ansicht.'),
    ('public', 'changelog', 'Veroeffentlichte Produkt-Changelog-Eintraege fuer User-Anzeige. Status: lebt. Schreibt Admin-Pfad; liest Changelog-Anzeige (User.last_seen_changelog-Abgleich).'),
    ('public', 'audit_log', 'Audit-Trail sicherheitsrelevanter Aktionen (Actor, Action, Target, IP). Status: lebt. Schreibt audit-loggende Pfade; liest Admin-/Compliance-Ansicht.'),
    ('public', 'objection_events', 'Einzel-Einwand-Ereignis pro Call mit Erfolgs-Status (Kind von conversation_logs). Status: lebt. Schreibt routes/app_routes.py:384; liest routes/app_routes.py:471/1389, routes/dashboard.py:736.'),
    ('public', 'ewb_ratings', 'Manuelle EWB-Quality-Ratings (3 binaere Kriterien) pro EWB einer Session, fuer Quality-Score. Status: lebt. Schreibt routes/admin_ewb.py:192; liest routes/admin_ewb.py:65/181.'),
    ('public', 'feedback', 'In-App-Nutzer-Feedback (Bug/Idee/Lob/Frage) mit Screenshot und Status-Workflow. Status: lebt. Schreibt Feedback-Widget-Pfad; liest Admin-/Founder-Feedback-Ansicht.'),
    ('public', 'planning_feedback_link', 'Verknuepfung Feedback <-> Planungs-Eintrag (Backlog-Tracking). Status: lebt. Schreibt/liest Admin-/Founder-Feedback-Planungs-Ansicht.'),
    ('public', 'prompt_versions', 'Versionierte LLM-Prompts pro Modul mit A/B-Default-Fallback. Status: lebt. Schreibt Prompt-Admin-Pfad; liest get_active_prompt_version() in services/.'),
    ('public', 'api_cost_log', 'Jeder API-Call mit eingefrorenem Wechselkurs und Rate (Founder Cost Dashboard, steuerlich korrekt). Status: lebt. Schreibt API-Call-Wrapper in services/; liest Founder-Cost-Dashboard.'),
    ('public', 'api_rates', 'Aktuelle API-Preise pro Provider/Modell, editierbar, historisch via active-Flag. Status: lebt. Schreibt Admin-Rate-Pflege; liest Cost-Berechnung (api_cost_log) + Dashboard.'),
    ('public', 'price_change_log', 'Manuell erkannte API-Preisaenderungen mit Impact-Berechnung. Status: write-only [ZOMBIE]. Schreibt routes/admin_dashboard.py:434; kein Reader.'),
    ('public', 'fixed_costs', 'Fixe Betriebskosten (Hetzner, Domain, Kontist etc.) mit USt und SKR03-Konto. Status: lebt. Schreibt Admin-Fixkosten-Pflege; liest Founder-Cost-Dashboard.'),
    ('public', 'revenue_log', 'Jede Stripe-Zahlung (invoice.payment_succeeded) mit USt-Split und Land. Status: lebt. Schreibt Stripe-Webhook-Handler; liest Founder-Revenue-Dashboard.'),
    ('public', 'exchange_rates', 'Taeglicher EZB-Wechselkurs (Frankfurter-API) zum Einfrieren in api_cost_log. Status: lebt. Schreibt FX-Sync-Job; liest Cost-Berechnung in services/.'),
    ('public', 'learning_cards', 'Persoenliche Lernkarten (Coach-Modul): KI-/User-Formulierungen mit Lernziel und Status. Status: lebt. Schreibt services/coaching_service.py; liest routes/learning.py:429+, services/coaching_service.py:65/170.'),
    ('public', 'coaching_reports', 'Woechentlicher Coaching-Report je User (Read-Through-Cache). Status: lebt (Read-Through-Wochen-Cache, D-03 — NICHT write-only). Schreibt services/coaching_service.py:351; liest services/coaching_service.py:195 + Dashboard.'),
    ('public', 'learning_events', 'Cross-Modul-Lernereignisse fuer Muster-Erkennung der Integration-Engine. Status: lebt. Schreibt services/integration_engine.py:54+ (log_learning_event); liest services/integration_engine.py:163+188 (raw-SQL Muster-Erkennung).'),
    ('public', 'crm_notes', 'Customer-Success-Notiz pro User (public-Schema, NICHT crm-Schema trotz Klassenname). Status: lebt. Schreibt/liest routes/admin_views.py:209, services/customer_success_service.py:48.'),
    ('public', 'calls', 'Zentraler Call-Datensatz der neuen Architektur (UUID-PK, Outcome/Coaching/Transkript-Storage). Status: lebt (neue Architektur Phase 08.23.2.A+). Schreibt/liest services/+routes/ der neuen Call-Pipeline.'),
    ('public', 'call_events', 'Append-only Event-Stream pro Call (Kind von calls) der neuen Architektur. Status: lebt (neue Architektur Phase 08.23.2.A+). Schreibt/liest Live-Call-Pipeline in services/.'),
    ('public', 'transcript_segments', 'Anonymisierte Transkript-Segmente pro Call (Kind von conversation_logs, Pipeline B). Status: lebt (neue Architektur Phase 08.23.2.A+). Schreibt Anonymisierungs-Pipeline; liest Analyse-/Anzeige-Pfad.'),
    ('public', 'tenant_orgs', 'UUID-Tenancy-Root parallel zur Integer-org_id (Bruecke via legacy_org_id), public-Schema. Status: Reserve/Foundation (FK-Aktivierung Phase 08.23.2.F). Schreibt/liest noch nicht aktiv — Foundation fuer UUID-Tenancy.'),
    ('crm', 'accounts', 'Account-Stammdaten je Tenant. Status: lebt (crm, RLS-isoliert). Schreibt/liest services/crm_service.py + routes/crm_export.py.'),
    ('crm', 'contacts', 'Ansprechpartner je Account/Tenant. Status: lebt (crm, RLS-isoliert). Schreibt/liest services/crm_service.py + routes/crm_export.py.'),
    ('crm', 'account_memory', 'MEDDPICC-Gedaechtnis je Account (PreCall-Briefing-Quelle). Status: lebt (Foundation, crm; D-02 — NICHT toter Import). Schreibt G-MEET-Pipeline; liest services/precall_service.py:175.'),
    ('crm', 'meetings', 'Termin-/Meeting-Datensaetze je Tenant (PiP-Termin-Form, G-MEET). Status: lebt (crm, RLS-isoliert). Schreibt/liest services/crm_service.py + routes/app_routes.py.'),
    ('crm', 'user_preferences', 'Nutzer-Praeferenzen je Tenant (z.B. auto_save_meeting DSGVO-Opt-in). Status: lebt (crm, RLS-isoliert). Schreibt/liest services/crm_service.py + routes/app_routes.py (g.user.id, MM-07).'),
    ('training', 'preference_pairs', 'DPO-Praeferenz-Triples (DPO-Foundation). Status: Reserve/Foundation (0 aktive Befueller; Phase 08.23.2.E befuellt). Schreibt noch nicht aktiv; liest spaeterer DPO-Trainings-Job.'),
    ('training', 'transcript_archive', 'Anonymisierungs-Rohmaterial der DPO-Pipeline (Pipeline B). Status: Reserve/Foundation (ORM-los, befuellt vom Anonymizer-Worker). Schreibt services/anonymization-Worker; liest Phase 08.23.2.E (DPO).'),
]

# (schema, table, column, comment)
COLUMN_COMMENTS = [
    ('public', 'organisations', 'name', 'Organisations-Name'),
    ('public', 'organisations', 'plan', 'Plan: starter/team/business/enterprise'),
    ('public', 'organisations', 'max_users', 'Maximale Nutzerzahl im Plan'),
    ('public', 'organisations', 'billing_email', 'Rechnungs-Email'),
    ('public', 'organisations', 'naechste_abrechnung', 'Naechster Abrechnungstermin'),
    ('public', 'organisations', 'trial_starts_at', 'Trial-Startzeitpunkt'),
    ('public', 'organisations', 'dsgvo_modus', 'DSGVO-Modus aktiv (kein woertliches Mitschneiden)'),
    ('public', 'organisations', 'plan_typ', 'Plan-Typ: training/live/bundle/coach'),
    ('public', 'organisations', 'training_free_calls', 'Freie Trainings-Calls'),
    ('public', 'organisations', 'live_free_trainings', 'Freie Live-Trainings'),
    ('public', 'organisations', 'billing_name', 'Rechnungs-Name'),
    ('public', 'organisations', 'billing_street', 'Rechnungs-Strasse'),
    ('public', 'organisations', 'billing_zip', 'Rechnungs-PLZ'),
    ('public', 'organisations', 'billing_city', 'Rechnungs-Stadt'),
    ('public', 'organisations', 'billing_country', 'Rechnungs-Land'),
    ('public', 'organisations', 'billing_vat_id', 'USt-IdNr.'),
    ('public', 'organisations', 'cancelled_at', 'Kuendigungszeitpunkt'),
    ('public', 'organisations', 'cancel_reason', 'Kuendigungsgrund'),
    ('public', 'organisations', 'cancel_feedback', 'Kuendigungs-Feedback'),
    ('public', 'organisations', 'early_access_discount', 'Early-Access-Rabatt in Prozent'),
    ('public', 'organisations', 'minuten_limit', 'Fair-Use Minuten-Limit pro User/Monat'),
    ('public', 'organisations', 'training_voice_limit', 'TTS-Trainings-Limit pro User/Monat'),
    ('public', 'organisations', 'plan_preis', 'Flat-Rate-Preis in Euro/Monat'),
    ('public', 'organisations', 'live_minutes_used', 'Verbrauchte Live-Minuten diesen Monat'),
    ('public', 'organisations', 'training_sessions_used', 'Gestartete Trainings diesen Monat'),
    ('public', 'organisations', 'fair_use_reset_month', "Fair-Use-Reset-Monat, z.B. '2026-04'"),
    ('public', 'organisations', 'stripe_customer_id', 'Stripe Customer-ID'),
    ('public', 'organisations', 'stripe_subscription_id', 'Stripe Subscription-ID'),
    ('public', 'organisations', 'stripe_price_id', 'Stripe Price-ID'),
    ('public', 'organisations', 'subscription_status', 'Subscription-Status'),
    ('public', 'users', 'email', 'Login-Email (eindeutig)'),
    ('public', 'users', 'passwort_hash', "Passwort-Hash; nullable fuer OAuth-User (OAuth setzt '' als Sentinel)"),
    ('public', 'users', 'rolle', 'Rolle: owner/admin/member'),
    ('public', 'users', 'letzte_aktivitaet', 'Zeitpunkt der letzten User-Aktivitaet'),
    ('public', 'users', 'trial_ends_at', 'Ablaufzeitpunkt der Trial-Phase'),
    ('public', 'users', 'vorname', 'Vorname'),
    ('public', 'users', 'nachname', 'Nachname'),
    ('public', 'users', 'onboarding_done', 'Flag: Onboarding abgeschlossen'),
    ('public', 'users', 'erfahrungslevel', 'Erfahrungslevel: einsteiger/fortgeschritten/profi'),
    ('public', 'users', 'schmerzpunkt', 'Onboarding: groesster Schmerzpunkt'),
    ('public', 'users', 'persoenlich', 'Onboarding: persoenliche Angaben'),
    ('public', 'users', 'streak_count', 'Aktuelle Streak-Laenge'),
    ('public', 'users', 'streak_last_date', 'Letztes Datum mit Aktivitaet (Streak)'),
    ('public', 'users', 'total_points', 'Gesamtpunkte (Gamification)'),
    ('public', 'users', 'level', 'Gamification-Level'),
    ('public', 'users', 'nudge_dismissed', 'JSON-Array: weggeklickte Nudges'),
    ('public', 'users', 'live_calls_used', 'Verbrauchte Live-Calls'),
    ('public', 'users', 'trainings_used', 'Verbrauchte Trainings'),
    ('public', 'users', 'notif_training_reminder', 'Notif-Praeferenz: Training-Reminder'),
    ('public', 'users', 'notif_streak_warning', 'Notif-Praeferenz: Streak-Warnung'),
    ('public', 'users', 'notif_achievements', 'Notif-Praeferenz: Achievements'),
    ('public', 'users', 'notif_coach', 'Notif-Praeferenz: Coach-Hinweise'),
    ('public', 'users', 'notif_nudges', 'Notif-Praeferenz: Nudges'),
    ('public', 'users', 'dashboard_stil', 'Dashboard-Stil-Praeferenz (Legacy)'),
    ('public', 'users', 'last_seen_changelog', 'Zuletzt gesehene Changelog-Version'),
    ('public', 'users', 'dashboard_style', 'Dashboard-Layout: vollstaendig/kompakt'),
    ('public', 'users', 'minuten_used', 'Verbrauchte Minuten diesen Monat'),
    ('public', 'users', 'trainings_voice_used', 'TTS-Trainings diesen Monat'),
    ('public', 'users', 'usage_reset_date', 'Datum des naechsten Usage-Resets'),
    ('public', 'users', 'preferred_language', 'Bevorzugte UI-Sprache'),
    ('public', 'users', 'preferred_theme', 'Bevorzugtes Theme: dark/light'),
    ('public', 'users', 'weekly_goal', 'Woechentliches Trainings-Ziel'),
    ('public', 'users', 'pending_training_recommendation', 'JSON: offene Trainings-Empfehlung der Integration-Engine'),
    ('public', 'users', 'avg_deal_wert', 'Durchschnittlicher Deal-Wert in Euro (NULL = nicht gesetzt)'),
    ('public', 'users', 'oauth_provider', "OAuth-Provider: 'google' | 'microsoft' | None"),
    ('public', 'users', 'oauth_id', 'OAuth Provider-Sub-ID (eindeutig pro Provider)'),
    ('public', 'users', 'avatar_url', 'Avatar-Bild-URL'),
    ('public', 'users', 'email_confirmed', 'Email bestaetigt (Microsoft-OAuth Hijacking-Mitigation, H-18)'),
    ('public', 'users', 'market', 'Markt fuer FT-Logging-Trennung (z.B. dach)'),
    ('public', 'users', 'language', 'Sprache des Nutzers (z.B. de)'),
    ('public', 'profiles', 'name', 'Profil-Name'),
    ('public', 'profiles', 'branche', 'Branche des Profils'),
    ('public', 'profiles', 'daten', 'JSON-Methodik-Container (einwaende/phasen/gegenargumente/ki/kaufsignale)'),
    ('public', 'profiles', 'erstellt_von', 'Ersteller-User (FK users.id)'),
    ('public', 'profiles', 'consent_text', 'Editierbarer Consent-Vorlesetext (Phase 06)'),
    ('public', 'profile_skripte', 'name', 'Skript-Name'),
    ('public', 'profile_skripte', 'inhalt', 'Skript-Inhalt'),
    ('public', 'profile_skripte', 'sortierung', 'Sortier-Reihenfolge'),
    ('public', 'profile_skripte', 'parent_id', 'Quell-Item-ID (ProfileSkript/ProfileOpener); D-04: kein FK-Constraint'),
    ('public', 'profile_skripte', 'briefing_source_firma', 'Firma aus PreCall-Briefing (Personalisierungs-Quelle)'),
    ('public', 'profile_faqs', 'frage_muster', 'Frage-Muster, gegen das gematcht wird'),
    ('public', 'profile_faqs', 'antwort', 'Hinterlegte Antwort'),
    ('public', 'profile_faqs', 'kategorie', 'Kategorie: Technik/Preis/Referenzen/DSGVO/Produkt/Sonstiges'),
    ('public', 'profile_faqs', 'used_count', 'Verwendungs-Zaehler'),
    ('public', 'profile_faqs', 'mode', 'Herkunft: ki_generated vs. manuell'),
    ('public', 'profile_opener', 'name', 'Opener-Name'),
    ('public', 'profile_opener', 'inhalt', 'Opener-Inhalt'),
    ('public', 'profile_opener', 'sortierung', 'Sortier-Reihenfolge'),
    ('public', 'profile_opener', 'type', 'Typ des Bausteins (z.B. opener)'),
    ('public', 'profile_opener', 'briefing_source_firma', 'Firma aus PreCall-Briefing (Personalisierungs-Quelle)'),
    ('public', 'sessions', 'token', 'Session-Token (eindeutig)'),
    ('public', 'sessions', 'ablauf_am', 'Ablaufzeitpunkt der Session'),
    ('public', 'invitations', 'email', 'Eingeladene Email-Adresse'),
    ('public', 'invitations', 'token', 'Einladungs-Token (eindeutig)'),
    ('public', 'invitations', 'verwendet', 'Flag: Einladung wurde bereits eingeloest'),
    ('public', 'billing_events', 'typ', 'Ereignis-Typ'),
    ('public', 'billing_events', 'betrag', 'Betrag in Euro'),
    ('public', 'billing_events', 'beschreibung', 'Beschreibung des Ereignisses'),
    ('public', 'billing_events', 'timestamp', 'Zeitpunkt des Ereignisses'),
    ('public', 'billing_events', 'stripe_event_id', 'Stripe-Event-ID (Idempotenz, eindeutig)'),
    ('public', 'feedback_events', 'session_log_id', 'Referenzierte Session-Log-ID'),
    ('public', 'feedback_events', 'stars', 'Stern-Bewertung'),
    ('public', 'feedback_events', 'comment', 'Freitext-Kommentar'),
    ('public', 'training_scenarios', 'name', 'Szenario-Name'),
    ('public', 'training_scenarios', 'beschreibung', 'Szenario-Beschreibung'),
    ('public', 'training_scenarios', 'kunde_situation', 'Situation des simulierten Kunden'),
    ('public', 'training_scenarios', 'kunde_verhalten', 'Verhalten des simulierten Kunden'),
    ('public', 'training_scenarios', 'spezial_einwaende', 'JSON-Array: spezielle Einwaende fuer dieses Szenario'),
    ('public', 'training_scenarios', 'schwierigkeit', 'Schwierigkeitsgrad: leicht/mittel/schwer'),
    ('public', 'training_scenarios', 'erstellt_von', 'Ersteller-User (FK users.id)'),
    ('public', 'personality_types', 'name', 'Name des Persoenlichkeitstyps'),
    ('public', 'personality_types', 'icon', 'Icon/Emoji des Typs'),
    ('public', 'personality_types', 'kurzbeschreibung', 'Kurzbeschreibung des Typs'),
    ('public', 'personality_types', 'attribute', 'JSON: Verhaltens-Attribute des Typs'),
    ('public', 'personality_types', 'kommentar', 'Freitext-Kommentar'),
    ('public', 'conversation_logs', 'profile_name', 'Profil-Name zum Zeitpunkt des Calls (Snapshot)'),
    ('public', 'conversation_logs', 'started_at', 'Call-Startzeitpunkt'),
    ('public', 'conversation_logs', 'ended_at', 'Call-Endzeitpunkt'),
    ('public', 'conversation_logs', 'dauer_sekunden', 'Call-Dauer in Sekunden'),
    ('public', 'conversation_logs', 'segmente_gesamt', 'Anzahl Transkript-Segmente gesamt'),
    ('public', 'conversation_logs', 'einwaende_gesamt', 'Anzahl erkannter Einwaende gesamt'),
    ('public', 'conversation_logs', 'einwaende_behandelt', 'Anzahl erfolgreich behandelter Einwaende'),
    ('public', 'conversation_logs', 'einwaende_fehlgeschlagen', 'Anzahl fehlgeschlagener Einwand-Behandlungen'),
    ('public', 'conversation_logs', 'einwaende_ignoriert', 'Anzahl ignorierter Einwaende'),
    ('public', 'conversation_logs', 'vorwaende_erkannt', 'Anzahl als Vorwand erkannter Einwaende'),
    ('public', 'conversation_logs', 'kb_start', 'Kaufbereitschaft Start-Wert (0-100)'),
    ('public', 'conversation_logs', 'kb_end', 'Kaufbereitschaft End-Wert (0-100)'),
    ('public', 'conversation_logs', 'kb_min', 'Kaufbereitschaft Minimum waehrend Call'),
    ('public', 'conversation_logs', 'kb_max', 'Kaufbereitschaft Maximum waehrend Call'),
    ('public', 'conversation_logs', 'redeanteil_avg', 'Durchschnittlicher Redeanteil Berater in Prozent'),
    ('public', 'conversation_logs', 'tempo_avg', 'Durchschnittliches Sprechtempo'),
    ('public', 'conversation_logs', 'laengster_monolog', 'Laengster Monolog in Sekunden'),
    ('public', 'conversation_logs', 'hilfe_genutzt', 'Anzahl genutzter Hilfe-/Coaching-Einblendungen'),
    ('public', 'conversation_logs', 'quick_actions', 'Anzahl ausgeloester Quick-Actions'),
    ('public', 'conversation_logs', 'skript_abdeckung', 'Skript-Abdeckung in Prozent'),
    ('public', 'conversation_logs', 'sterne', 'Manuelle Stern-Bewertung des Calls (1-5)'),
    ('public', 'conversation_logs', 'kommentar', 'Manueller Kommentar zum Call'),
    ('public', 'conversation_logs', 'gegenargument_details', 'JSON: Detail-Daten zu Gegenargumenten'),
    ('public', 'conversation_logs', 'painpoints_details', 'JSON: Detail-Daten zu erkannten Painpoints'),
    ('public', 'conversation_logs', 'phasen_details', 'JSON: Detail-Daten zu Gespraechsphasen'),
    ('public', 'conversation_logs', 'typ', 'Call-Typ: live oder training'),
    ('public', 'conversation_logs', 'session_mode', "Modus: 'cold_call' oder 'meeting'"),
    ('public', 'conversation_logs', 'result', "Call-Ergebnis: 'gewonnen' | 'verloren' | NULL"),
    ('public', 'conversation_logs', 'market', 'Markt fuer FT-Logging-Trennung (z.B. dach)'),
    ('public', 'conversation_logs', 'language', 'Sprache des Calls (z.B. de)'),
    ('public', 'conversation_logs', 'stimmung_history', 'JSON-Liste: Stimmungs-Verlauf waehrend Call'),
    ('public', 'conversation_logs', 'precall_briefing', 'Generiertes Call-Briefing (D-03: nur Briefing-Text, keine Roh-Suchdaten)'),
    ('public', 'conversation_logs', 'precall_fields', 'JSON: strukturierte Schicht-1-Felder (D-03: keine Roh-Suchdaten)'),
    ('public', 'conversation_logs', 'kb_verlauf', 'JSON-Liste: Kaufbereitschafts-Verlauf [{ts, wert 0-100}] fuer Chart'),
    ('public', 'conversation_logs', 'anrede', 'PreCall-Anrede-Override (Du/Sie); Fallback: Profile.daten.ki.ansprache'),
    ('public', 'phrases', 'text', 'Anonymisierter Phrasen-Text (Einwand)'),
    ('public', 'phrases', 'objection_type', 'Einwand-Typ-Klassifikation'),
    ('public', 'phrases', 'quality_tier', "Anonymisierungs-Qualitaet: 'A'=sauber, 'B'=Edge-Case-NER, 'C'=Art9/Exception"),
    ('public', 'phrases', 'mode', 'Phasen-Diskriminator: gatekeeper vs. cold_call/meeting (CHECK ck_phrases_mode)'),
    ('public', 'waitlist', 'email', 'Email (eindeutig)'),
    ('public', 'waitlist', 'name', 'Name'),
    ('public', 'waitlist', 'firma', 'Firma'),
    ('public', 'waitlist', 'rolle', 'Rolle/Position im Unternehmen'),
    ('public', 'waitlist', 'branche', 'Branche'),
    ('public', 'waitlist', 'nachricht', 'Freitext-Nachricht'),
    ('public', 'waitlist', 'position', 'Position in der Warteliste'),
    ('public', 'waitlist', 'status', 'Status: waiting/invited/registered/declined'),
    ('public', 'waitlist', 'invited_at', 'Zeitpunkt der Einladung'),
    ('public', 'waitlist', 'registered_at', 'Zeitpunkt der Registrierung'),
    ('public', 'waitlist', 'referral_code', 'Eigener Referral-Code'),
    ('public', 'waitlist', 'referred_by', 'Referral-Code des Werbers'),
    ('public', 'changelog', 'version', 'Versions-String des Eintrags'),
    ('public', 'changelog', 'titel', 'Titel des Eintrags'),
    ('public', 'changelog', 'inhalt', 'Inhalt/Beschreibung'),
    ('public', 'changelog', 'typ', 'Typ: major/feature/improvement/bugfix/security'),
    ('public', 'changelog', 'bekannte_bugs', 'JSON-Array: bekannte Bugs'),
    ('public', 'changelog', 'veroeffentlicht', 'Sichtbarkeits-Flag: Changelog-Eintrag veroeffentlicht'),
    ('public', 'audit_log', 'action', 'Durchgefuehrte Aktion'),
    ('public', 'audit_log', 'target_type', 'Typ des betroffenen Objekts'),
    ('public', 'audit_log', 'target_id', 'ID des betroffenen Objekts'),
    ('public', 'audit_log', 'details', 'JSON/Freitext: Aktions-Details'),
    ('public', 'audit_log', 'ip_address', 'IP-Adresse des Actors'),
    ('public', 'audit_log', 'user_agent', 'User-Agent des Actors'),
    ('public', 'objection_events', 'einwand_typ', 'Einwand-Typ-Klassifikation'),
    ('public', 'objection_events', 'success', '3-State: TRUE=Erfolg, FALSE=kein Erfolg, NULL=uebersprungen/unbekannt'),
    ('public', 'objection_events', 'antwort_text', 'Persistierter Claude-Antwort-Text (fuer Rating-Page)'),
    ('public', 'objection_events', 'einwand_text', 'Original-Einwand-Text des Kunden'),
    ('public', 'ewb_ratings', 'einwand_typ_key', 'Einwand-Typ-Key (matched gegen ObjectionEvent.einwand_typ)'),
    ('public', 'ewb_ratings', 'klingt_wie_mensch', 'Sub-Kriterium: klingt wie Mensch'),
    ('public', 'ewb_ratings', 'keine_halluzination', 'Sub-Kriterium: keine Halluzination (doppelt gewichtet)'),
    ('public', 'ewb_ratings', 'trifft_einwand', 'Sub-Kriterium: trifft den Einwand'),
    ('public', 'ewb_ratings', 'rated_at', 'Zeitpunkt der Bewertung'),
    ('public', 'feedback', 'typ', "Feedback-Typ: 'bug'|'idea'|'praise'|'question'"),
    ('public', 'feedback', 'text', 'Feedback-Text'),
    ('public', 'feedback', 'screenshot_path', "Relativer Screenshot-Pfad: 'feedback/{uuid}.png'"),
    ('public', 'feedback', 'context_url', 'URL, auf der das Feedback gegeben wurde'),
    ('public', 'feedback', 'status', 'Status: new|seen|in_planning|done|wont_fix'),
    ('public', 'feedback', 'kategorie', 'Kategorie des Feedbacks'),
    ('public', 'feedback', 'rating', 'Quick-Rating 1-5'),
    ('public', 'feedback', 'notification_sent', 'Flag: Benachrichtigung ueber dieses Feedback wurde versendet'),
    ('public', 'planning_feedback_link', 'planning_title', 'Titel des Planungs-Eintrags'),
    ('public', 'planning_feedback_link', 'planning_status', 'Planungs-Status: backlog|active|done'),
    ('public', 'prompt_versions', 'version', 'Prompt-Versions-String'),
    ('public', 'prompt_versions', 'module', 'Modul, zu dem der Prompt gehoert'),
    ('public', 'prompt_versions', 'prompt_text', 'Prompt-Text'),
    ('public', 'prompt_versions', 'changelog', 'Changelog zur Prompt-Version'),
    ('public', 'api_cost_log', 'provider', 'API-Provider (z.B. anthropic/deepgram)'),
    ('public', 'api_cost_log', 'model', 'Verwendetes Modell'),
    ('public', 'api_cost_log', 'units', 'Verbrauchte Einheiten'),
    ('public', 'api_cost_log', 'unit_type', 'Einheiten-Typ (z.B. tokens/minutes)'),
    ('public', 'api_cost_log', 'rate_applied', 'Angewandte (eingefrorene) Rate'),
    ('public', 'api_cost_log', 'rate_currency', 'Waehrung der Rate'),
    ('public', 'api_cost_log', 'fx_rate_applied', 'Eingefrorener Wechselkurs (D-02)'),
    ('public', 'api_cost_log', 'cost_eur', 'Berechnete Kosten in Euro'),
    ('public', 'api_cost_log', 'session_id', 'Zugehoerige Session-ID'),
    ('public', 'api_cost_log', 'context_tag', 'Kontext-Tag des Calls'),
    ('public', 'api_cost_log', 'latency_ms', 'API-Latenz in ms'),
    ('public', 'api_cost_log', 'call_site', 'Code-Aufrufstelle'),
    ('public', 'api_rates', 'provider', 'API-Provider'),
    ('public', 'api_rates', 'model', 'Modell'),
    ('public', 'api_rates', 'unit_type', 'Einheiten-Typ'),
    ('public', 'api_rates', 'price_per_unit', 'Preis pro Einheit'),
    ('public', 'api_rates', 'currency', 'Waehrung'),
    ('public', 'api_rates', 'active', 'Aktiv-Flag: nur die aktuell gueltige Rate ist aktiv (Historie ueber active)'),
    ('public', 'api_rates', 'last_checked_at', 'Zeitpunkt letzter Preis-Pruefung'),
    ('public', 'api_rates', 'source_url', 'Quell-URL der Preisangabe'),
    ('public', 'price_change_log', 'changed_at', 'Zeitpunkt der Preisaenderung'),
    ('public', 'price_change_log', 'old_rate', 'Alte Rate'),
    ('public', 'price_change_log', 'new_rate', 'Neue Rate'),
    ('public', 'price_change_log', 'currency', 'Waehrung'),
    ('public', 'price_change_log', 'impact_eur_per_month', 'Geschaetzter Impact in Euro/Monat'),
    ('public', 'price_change_log', 'note', 'Notiz zur Preisaenderung'),
    ('public', 'fixed_costs', 'name', 'Bezeichnung der Fixkosten-Position'),
    ('public', 'fixed_costs', 'amount_eur', 'Betrag in Euro'),
    ('public', 'fixed_costs', 'vat_rate', 'USt-Satz in Prozent'),
    ('public', 'fixed_costs', 'cycle', "Abrechnungs-Zyklus: 'monthly'|'yearly'|'per_day'"),
    ('public', 'fixed_costs', 'skr03', 'SKR03-Kontonummer'),
    ('public', 'fixed_costs', 'eur_line', 'EUER-Zeilennummer'),
    ('public', 'fixed_costs', 'active', 'Aktiv-Flag: Fixkosten-Posten aktuell gueltig'),
    ('public', 'revenue_log', 'stripe_invoice_id', 'Stripe-Invoice-ID (eindeutig, Idempotenz)'),
    ('public', 'revenue_log', 'stripe_customer_id', 'Stripe-Customer-ID'),
    ('public', 'revenue_log', 'paid_at', 'Zahlungszeitpunkt'),
    ('public', 'revenue_log', 'netto_cents', 'Netto-Betrag in Cent'),
    ('public', 'revenue_log', 'ust_cents', 'USt-Betrag in Cent'),
    ('public', 'revenue_log', 'brutto_cents', 'Brutto-Betrag in Cent'),
    ('public', 'revenue_log', 'currency', 'Waehrung'),
    ('public', 'revenue_log', 'country', 'Laenderkennung (ISO-2)'),
    ('public', 'revenue_log', 'tax_treatment', "Steuer-Behandlung: 'DE_19'|'EU_RC'|'DRITTLAND'"),
    ('public', 'revenue_log', 'plan_key', 'Plan-Schluessel der Zahlung'),
    ('public', 'revenue_log', 'raw_json', 'Roh-JSON des Stripe-Events'),
    ('public', 'exchange_rates', 'date', 'Kurs-Datum'),
    ('public', 'exchange_rates', 'currency_pair', "Waehrungspaar, z.B. 'USD_EUR'"),
    ('public', 'exchange_rates', 'rate', 'Wechselkurs'),
    ('public', 'exchange_rates', 'source', 'Kurs-Quelle'),
    ('public', 'learning_cards', 'category', 'Kategorie der Lernkarte'),
    ('public', 'learning_cards', 'original_suggestion', 'Urspruenglicher KI-Vorschlag'),
    ('public', 'learning_cards', 'final_text', 'Finaler (ggf. editierter) Karten-Text'),
    ('public', 'learning_cards', 'lernziel', 'Lernziel der Karte'),
    ('public', 'learning_cards', 'source', "Quelle: 'ki' | 'user'"),
    ('public', 'learning_cards', 'status', "Status: 'vorschlag' | 'aktiv' | 'gelernt' | 'archiviert'"),
    ('public', 'learning_cards', 'applied_count', 'Wie oft angewendet'),
    ('public', 'learning_cards', 'regenerate_count', 'Wie oft neu generiert'),
    ('public', 'learning_cards', 'learned_at', 'Zeitpunkt als gelernt markiert'),
    ('public', 'coaching_reports', 'period_start', 'Wochen-Start des Report-Zeitraums'),
    ('public', 'coaching_reports', 'period_end', 'Wochen-Ende des Report-Zeitraums'),
    ('public', 'coaching_reports', 'calls_count', 'Anzahl Calls im Zeitraum'),
    ('public', 'coaching_reports', 'avg_readiness_score', 'Durchschnittlicher Readiness-Score im Zeitraum'),
    ('public', 'coaching_reports', 'strongest_phase', 'Staerkste Gespraechsphase'),
    ('public', 'coaching_reports', 'weakest_phase', 'Schwaechste Gespraechsphase'),
    ('public', 'coaching_reports', 'talk_ratio_user', 'Redeanteil Berater'),
    ('public', 'coaching_reports', 'talk_ratio_customer', 'Redeanteil Kunde'),
    ('public', 'coaching_reports', 'report_text', 'Generierter Coaching-Report-Text (Dashboard-Anzeige)'),
    ('public', 'coaching_reports', 'suggested_card_json', 'JSON: vorgeschlagene Lernkarte aus dem Report'),
    ('public', 'learning_events', 'event_type', 'Art des Lernereignisses'),
    ('public', 'learning_events', 'source_module', 'Ursprungs-Modul des Ereignisses'),
    ('public', 'learning_events', 'source_id', 'ID des Quell-Objekts im Ursprungs-Modul'),
    ('public', 'learning_events', 'metadata', 'JSON: ereignisspezifische Metadaten'),
    ('public', 'crm_notes', 'notiz', 'Freitext-Notiz zum User (Customer Success)'),
    ('public', 'calls', 'call_mode', "Call-Modus: 'cold_call' | 'meeting_consented' (CHECK ck_calls_call_mode)"),
    ('public', 'calls', 'call_type', 'Optionale Call-Typ-Klassifikation'),
    ('public', 'calls', 'started_at', 'Call-Startzeitpunkt (tz-aware)'),
    ('public', 'calls', 'ended_at', 'Call-Endzeitpunkt (tz-aware)'),
    ('public', 'calls', 'transcript_storage', "Transkript-Speichermodus: 'none'|'ephemeral'|'consented_full' (DSGVO, CHECK)"),
    ('public', 'calls', 'transcript_expires_at', 'Ablaufzeitpunkt fuer ephemeres Transkript (DSGVO)'),
    ('public', 'calls', 'call_summary', 'Post-Call-Zusammenfassung'),
    ('public', 'calls', 'outcome', 'Call-Ergebnis (CHECK ck_calls_outcome, z.B. meeting_booked/no_interest)'),
    ('public', 'calls', 'audio_health_score', 'Audio-Qualitaets-Score des Calls'),
    ('public', 'calls', 'coaching_score', 'Gesamt-Coaching-Score des Calls'),
    ('public', 'calls', 'score_breakdown', 'JSON: Aufschluesselung des Coaching-Scores'),
    ('public', 'calls', 'score_schema_version', 'Schema-Version des score_breakdown'),
    ('public', 'calls', 'outcome_confidence', 'KI-Konfidenz der Outcome-Klassifikation (0-1)'),
    ('public', 'calls', 'outcome_note', 'Notiz zum Outcome'),
    ('public', 'calls', 'outcome_source', "Outcome-Quelle: 'ai_auto'|'ai_auto_unsicher'|'user_corrected' (CHECK)"),
    ('public', 'calls', 'followup_intent', "Follow-up-Absicht: 'none'|'callback'|'meeting'|'send_info'|'retry_internal' (CHECK)"),
    ('public', 'calls', 'meddpicc_extracted', 'JSON: aus Call extrahierte MEDDPICC-Felder'),
    ('public', 'call_events', 'event_type', 'Event-Typ (CHECK ck_call_events_event_type, z.B. transcript_chunk/objection_detected)'),
    ('public', 'call_events', 'event_ts_ms', 'Event-Zeitstempel in Unix-ms (BIGINT, 2038-sicher)'),
    ('public', 'call_events', 'payload', 'JSON: event-spezifische Nutzdaten (GIN-indiziert)'),
    ('public', 'transcript_segments', 'ts_ms', 'ms ab Call-Start, fuer Reihenfolge'),
    ('public', 'transcript_segments', 'speaker', "Sprecher: 'berater'|'kunde'|'system' (CHECK)"),
    ('public', 'transcript_segments', 'text', 'Anonymisierter Segment-Text (Pipeline B)'),
    ('public', 'tenant_orgs', 'legacy_org_id', 'Bruecke zur Integer-organisations.id (Tenancy-Migration)'),
    ('public', 'tenant_orgs', 'name', 'Tenant-/Organisations-Name'),
    ('crm', 'accounts', 'name', 'Account-/Firmen-Name'),
    ('crm', 'accounts', 'domain', 'Firmen-Domain'),
    ('crm', 'contacts', 'name', 'Kontakt-Name'),
    ('crm', 'contacts', 'email', 'Kontakt-Email'),
    ('crm', 'contacts', 'phone', 'Kontakt-Telefon'),
    ('crm', 'account_memory', 'schema_version', 'Schema-Version des MEDDPICC-Memory-Datensatzes (D-19)'),
    ('crm', 'account_memory', 'meddpicc', 'MEDDPICC-JSONB (8 ASCII-Keys: metrics/economic_buyer/decision_criteria/decision_process/paper_process/pain/champion/competition)'),
    ('crm', 'account_memory', 'context_hooks', 'JSON-Array: Kontext-Hooks fuer PreCall-Briefing'),
    ('crm', 'account_memory', 'last_call_summary', 'Zusammenfassung des letzten Calls'),
    ('crm', 'account_memory', 'anonymized_at', 'Anonymisierungs-Zeitpunkt (Variante A state-tracking, Wave 3)'),
    ('crm', 'meetings', 'call_id', 'Soft-Link zu public.calls.id, KEIN FK (D-08)'),
    ('crm', 'meetings', 'scheduled_at', 'Geplanter Meeting-Zeitpunkt'),
    ('crm', 'meetings', 'notes', 'Meeting-Notizen'),
    ('crm', 'meetings', 'schema_version', 'Schema-Version des Meeting-Datensatzes'),
    ('crm', 'user_preferences', 'auto_save_meeting', 'DSGVO Opt-in (Art. 25 Abs. 2), default OFF, serverseitig gehonort'),
    ('crm', 'user_preferences', 'schema_version', 'Schema-Version des User-Preference-Datensatzes'),
    ('training', 'preference_pairs', 'prompt', 'JSON: DPO-Prompt (Kontext/Einwand)'),
    ('training', 'preference_pairs', 'chosen', 'JSON: bevorzugte (chosen) Antwort im DPO-Triple'),
    ('training', 'preference_pairs', 'rejected', 'JSON: abgelehnte (rejected) Antwort im DPO-Triple'),
    ('training', 'preference_pairs', 'batch_id', 'Batch-Gruppierung der Generierung'),
    ('training', 'preference_pairs', 'anonymizer_version', 'Version der Anonymisierungs-Pipeline'),
    ('training', 'preference_pairs', 'source_call_hash', 'Einweg-Hash der Quell-Call (D-17, kein call_id-FK ueber die DSGVO-Mauer)'),
    ('training', 'preference_pairs', 'labeller', 'Labeller-Kennung'),
    ('training', 'preference_pairs', 'rating_chosen', 'Rating der chosen-Antwort'),
    ('training', 'preference_pairs', 'rating_rejected', 'Rating der rejected-Antwort'),
    ('training', 'preference_pairs', 'rationale', 'Begruendung der Praeferenz'),
    ('training', 'preference_pairs', 'split', "Datensatz-Split: 'train'|'val'|'test' (CHECK ck_preference_pairs_split)"),
    ('training', 'preference_pairs', 'schema_version', 'Schema-Version des Preference-Pair-Datensatzes (D-19)'),
    ('training', 'transcript_archive', 'source_call_hash', 'Einweg-Hash des Quell-Calls (DSGVO-Mauer, KEIN call_id-FK, D-17).'),
    ('training', 'transcript_archive', 'segment_index', 'Reihenfolge-Index des Transkript-Segments im Call.'),
    ('training', 'transcript_archive', 'speaker', "Sprecher-Label des Segments ('berater'|'kunde'|'system', CHECK)."),
    ('training', 'transcript_archive', 'text', 'Anonymisierter Segment-Text (Pipeline B, keine Klarnamen).'),
    ('training', 'transcript_archive', 'ts_offset_ms', 'Zeit-Offset des Segments ab Call-Start in Millisekunden.'),
    ('training', 'transcript_archive', 'schema_version', 'Schema-Version des Archiv-Datensatzes.'),
    ('training', 'transcript_archive', 'archived_at', 'Zeitpunkt der Archivierung (Anonymizer-Lauf).'),
]


def _q(s):
    """Postgres single-quote escape (double the quote)."""
    return s.replace("'", "''")


def upgrade():
    for schema, table, comment in TABLE_COMMENTS:
        op.execute("COMMENT ON TABLE %s.%s IS '%s'" % (schema, table, _q(comment)))
    for schema, table, column, comment in COLUMN_COMMENTS:
        op.execute("COMMENT ON COLUMN %s.%s.%s IS '%s'" % (schema, table, column, _q(comment)))


def downgrade():
    for schema, table, comment in TABLE_COMMENTS:
        op.execute("COMMENT ON TABLE %s.%s IS NULL" % (schema, table))
    for schema, table, column, comment in COLUMN_COMMENTS:
        op.execute("COMMENT ON COLUMN %s.%s.%s IS NULL" % (schema, table, column))
